### ISSUE TITLE
Start with an imported file

### ISSUE THREAD

**Issue by ZLLentz** [slaclab/timechart#23]
In PCDS, we use the striptool with preconfigured files 99% of the time. If we could do the same thing in `timechart` that would be awesome.

for example, `timechart --import <filename>` or any equivalent

**Comment by hmbui** [comment]
The code fix has been merged, and v1.0.1 will be available soon.

**Comment by hmbui** [comment]
Reopening the issue to keep track of the second part of the report -- TimeChart should also be able to import Strip Tool config files.
