### ISSUE TITLE
Add ability to collapse top/bottom areas (fullscreen-like mode)

### ISSUE THREAD

**Issue by ZLLentz** [slaclab/timechart#26]
Once my timechart is set up correctly I might want the view to be bigger. This isn't super crucial but I expect people to ask for this when we start deploying the application.

**Comment by hhslepicka** [comment]
@ZLLentz do you mean the `Add Channel` area?

**Comment by kabanaty** [comment]
[https://github.com/slaclab/timechart/pull/70](url)

**Comment by kabanaty** [comment]
#[https://github.com/slaclab/timechart/pull/70](url)
