### ISSUE TITLE
Exception Being Raised in Timechart update_curve_data

### ISSUE THREAD

**Issue by teddyrendahl** [slaclab/timechart#31]
It looks like we are searching for a child that doesn't exist. `findChild` will return `None` and then when we call `findChild` again on what we except to be a widget but is instead `None` the exception gets raised

https://github.com/slaclab/timechart/blob/e70ed45ee220cd7605ef972f2ecab99d8bc2aef0/timechart/displays/main_display.py#L1139

Please see:
https://github.com/teddyrendahl/typhon/blob/timechart/typhon/tools/plot.py
https://travis-ci.org/teddyrendahl/typhon/jobs/453048315

Where should these `_grb` widgets be added?

**Comment by teddyrendahl** [comment]
Found the issue. There is an assumption that `curveName` and `channel` are the same while `add_Y_Channel` supports them being different

https://github.com/slaclab/timechart/blob/e70ed45ee220cd7605ef972f2ecab99d8bc2aef0/timechart/displays/main_display.py#L1132

**Comment by hmbui** [comment]
Name and channel definitely need to be considered separately in TimeChart. I'll have a fix for this.
