### ISSUE TITLE
Dependency on PyDMApplication

### ISSUE THREAD

**Issue by teddyrendahl** [slaclab/timechart#35]
Now that it is no longer necessary to have `PyDMApplication` `timechart` should support basic `QApplication. There are multiple calls to `QApplication.instance().estabish_widget_connections` these should check if that attribute exists or not before calling. Either that or delete these calls entirely and have the module depend on the latest `pydm` version.

Thoughts @hhslepicka ?

**Comment by hhslepicka** [comment]
That is true. I would be in favor of the second option... Depende on the latest: `pydm >= 1.6.0` and move forward.
This tool is new and it would be a pity to start adding catches for a change on PyDM this soon.

**Comment by klauer** [comment]
This was closed in #34.
