### ISSUE TITLE
Usage comments

### ISSUE THREAD

**Issue by williamColocho** [slaclab/timechart#56]
Here are some usage comments:
~12 klicks to load / find a .stp file for import - Default directory should be more useful
No way to filter file names to find the one desired
Imported file name should be on main window
Add print to physics and operations logbook
Add save data to disk

**Comment by klauer** [comment]
I think I captured most of these in separate issues with room for discussion. Thanks for the feedback, @williamColocho.

We may tackle some of these as part of the EPICS Codeathon that's going on this week at SLAC.
