### ISSUE TITLE
Timechart Incompatible with Font Awesome Update in pydm=1.11.0

### ISSUE THREAD

**Issue by ZLLentz** [slaclab/timechart#57]
Some of the keywords for the icons changed slightly in https://github.com/slaclab/pydm/commit/a9cb2414a80d7821aebd11158f15a4247fd28a09, so with the newest pydm installed we cannot quite run our `typhos` app with `timechart` support.

I have a fix incoming but conda install is taking forever so I'm documenting in an issue first.

**Comment by hhslepicka** [comment]
@ZLLentz thanks for looking into it...
