### ISSUE TITLE
Errors thrown when adding PV to TimeChart

### ISSUE THREAD

**Issue by kabanaty** [slaclab/timechart#59]
After connecting to a PV in TimeChart, a large error gets thrown several times a second.    

> Traceback (most recent call last):
>   File "/afs/slac/g/lcls/package/anaconda/envs/python3_devel/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 302, in prepareForPaint
>     self.updateAutoRange()
>   File "/afs/slac/g/lcls/package/anaconda/envs/python3_devel/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 930, in updateAutoRange
>     childRange = self.childrenBounds(frac=fractionVisible)
>   File "/afs/slac/g/lcls/package/anaconda/envs/python3_devel/lib/python3.8/site-packages/pyqtgraph/graphicsItems/ViewBox/ViewBox.py", line 1428, in childrenBounds
>     xr = item.dataBounds(0, frac=frac[0], orthoRange=orthoRange[0])
>   File "/afs/slac/g/lcls/package/anaconda/envs/python3_devel/lib/python3.8/site-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 1106, in dataBounds
>     range = self.curve.dataBounds(ax, frac, orthoRange)
>   File "/afs/slac/g/lcls/package/anaconda/envs/python3_devel/lib/python3.8/site-packages/pyqtgraph/graphicsItems/PlotCurveItem.py", line 246, in dataBounds
>     if frac >= 1.0:
> TypeError: '>=' not supported between instances of 'NoneType' and 'float'
>

**Comment by klauer** [comment]
This is now fixed in the master branch of pydm. Probably can close this for now?
