### ISSUE TITLE
Enhancement: Application Startup Script

### ISSUE THREAD

**Issue by zdomke** [slaclab/timechart#72]
Create a startup script for the Timechart application.
This script should/could:

- Source the correct environment
- Process arguments and macros
- Take in PVs on startup (related to #63)

**Comment by klauer** [comment]
Where do these scripts usually sit for the accelerator side?

Should it go in this repository or somewhere else on AFS like that `use_python3.sh` script does?

Also, I learned about this recently: `conda run`
https://docs.conda.io/projects/conda/en/latest/commands/run.html
Something like this might even be enough if conda is in your path usually:

```bash
#!/bin/bash
conda run -e environment_name_here timechart "$@"
```

**Comment by zdomke** [comment]
What I've done on a previous project was use CRAM to push my application to `$TOOLS/script/release/{tool_name} ` . Then I add a symbolic link from `$TOOLS/script/{tool_name}  -> $TOOLS/script/release/{tool_name}/{release_name}/timechart.sh` . My application is ValidatePVs as a reference.

I'm not sure how standard that is though.

**Comment by klauer** [comment]
Conventions at SLAC are everything - they're "standards" in their own strange ways. What you describe seems reasonable to me 👍
